### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by hkennyv** [netlify/netlify-identity-widget#318]
Hey all,

It seems like there is an error when using netlify-identity-widget 1.8.0. This error is not present when reverting netlify-identity-widget back to 1.6.0. 

Some steps to reproduce this error:

* clone the repository [here](https://github.com/cassidoo/members-only) (I was following along with this [article](https://www.netlify.com/blog/2020/07/15/integrating-netlify-identity-into-your-next.js-apps/))
* install deps - `yarn install`
* try to run dev server - `yarn dev`

To get rid of this error by reverting back to 1.6.0:

* delete node_modules - `rm -rf node_modules/`
* change version of netlify-identity-widget from ^1.8.0 to 1.6.0 in **package.json**
* reinstall deps - `yarn install`
* start dev server - `yarn dev`  

The error is posted below:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/khuynh/me/develop/web/nextapp/node_modules/netlify-identity-widget/build/netlify-identity.js:1:212)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///netlify-identity-widget:1:18)
    at Object.netlify-identity-widget (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:416:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./utils/netlifyAuth.js:2:81)
    at Module../utils/netlifyAuth.js (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:382:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
    at eval (webpack-internal:///./pages/index.tsx:5:76)
    at Module../pages/index.tsx (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:347:1)
    at __webpack_require__ (/Users/khuynh/me/develop/web/nextapp/.next/server/static/development/pages/index.js:29:31)
```

**Comment by hkennyv** [comment]
It seems like it's an issue with the **webpack.umd.config.js** configuration. I set `output.globalObject = "this"` and rebuilt the package and it seems to fix it.

Following the issue on webpack [here](https://github.com/webpack/webpack/issues/6642). It looks like they have a [solution](https://github.com/webpack/webpack/issues/6525) in the works as well.

I'm attaching a PR!

**Comment by jlengstorf** [comment]
just confirmed this working with `v1.8.1` — let me know if you see any additional issues!
